# TODO: Similar to image template, this also needs to be configurable and not
#       like this with hardcoded values 
container:
  image: "my-template"
  name: "" # Optional: defaults to folder name
  user: "hans"
  cwd: "~CONTAINER_HOME~/workspace"
  # Here define only env vars that need to passed from host to container 
  # All others (especially project related) can be handled by mise
  env:
    OPENAI_MODEL_NAME: "${OPENAI_MODEL_NAME}"
    OPENAI_BASE_URL: "${OPENAI_BASE_URL}"
mounts:
  - source: "${PWD}"
    target: "~CONTAINER_HOME~/workspace"
    writeable: true
  - source: "${HOME}/.bashrc"
    target: "~CONTAINER_HOME~/.bashrc"
    writeable: true
  - source: "${HOME}/.config/git"
    target: "~CONTAINER_HOME~/.config/git"
    writeable: true
  - source: "${HOME}/.config/tmux/config"
    target: "~CONTAINER_HOME~/.config/tmux/config"
    writeable: true
  - source: "${HOME}/.config/tmux/tmux.conf"
    target: "~CONTAINER_HOME~/.config/tmux/tmux.conf"
    writeable: true
  - source: "${HOME}/.config/opencode"
    target: "~CONTAINER_HOME~/.config/opencode"
    writeable: true
