# TODO: Similar to image template, this also needs to be configurable and not
#       like this with hardcoded values 
container:
  image: "dev-template"
  name: "" # Optional: defaults to folder name
  user: "dev"
  cwd: "/home/dev/workspace"
  # Here define only env vars that need to passed from host to container 
  # All others (especially project related) can be handled by mise
  env:
    OPENAI_MODEL_NAME: "${OPENAI_MODEL_NAME}"
    OPENAI_BASE_URL: "${OPENAI_BASE_URL}"
mounts:
  - source: "${PWD}"
    target: "/home/dev/workspace"
    writeable: true
  - source: "${HOME}/.bashrc"
    target: "/home/dev/.bashrc"
    writeable: true
  - source: "${HOME}/.config/git"
    target: "/home/dev/.config/git"
    writeable: true
  - source: "${HOME}/.config/tmux/config"
    target: "/home/dev/.config/tmux/config"
    writeable: true
  - source: "${HOME}/.config/tmux/tmux.conf"
    target: "/home/dev/.config/tmux/tmux.conf"
    writeable: true
  - source: "${HOME}/.config/opencode"
    target: "/home/dev/.config/opencode"
    writeable: true
